name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - dev
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chabad360/hugo-actions@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 'files'
          container_name: '$migration-resources'
          connection_string: ${{ secrets.ConnectionString }}
          sync: true
