name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - dev
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - uses: LanceMcCarthy/Action-AzureBlobUpload@vX.X.X
        name: Uploading to Azure storage...
        with:
         connection_string: ${{ secrets.ConnectionString }}
         container_name: migration-resources
         source_folder: files
