name: Upload To Azure Blob Storage
#test
on:
  push:
    branches:
      - upload_to_blob
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        name: Uploading to Azure storage...
        with:
         connection_string: ${{ secrets.ConnectionString }}
         container_name: migration-resources
         source_folder: migration-resources
         clean_destination_folder: true
         is_recursive: true
